pull_request_rules:
  - name: automatic merge when CI passes and 1 review
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=continuous-integration/travis-ci/pr
      - base=master
    actions:
      merge:
        method: rebase
        rebase_fallback: squash
